---

# zsh
- name: install zsh
  become: yes
  apt:
    name:
      - zsh
    state: latest

- name: setup zsh as default shell
  become: yes
  user: 
    name: root
    shell: /bin/zsh
  user: 
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

# oh-my-zsh
- name: install oh-my-zsh
  shell: 
    - sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)" "" --unattended
    - chsh -s $(which zsh)
  
